name: Build and test
on:
  push:
    branches:
      - main
      - master
      - develop
      - spl2-tests # TODO: remove

jobs:
  unit-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
  functional-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install
    - run: npm run compile-tests
    - run: echo "Run acceptance tests" && node ./out/test/runFunctionalTests.js
      if: runner.os == 'macOS'
    - run: echo "Run acceptance tests" && xvfb-run -a node ./out/test/runFunctionalTests.js
      if: runner.os == 'Linux'
    - run: echo "Run acceptance tests" && node .\out\test\runFunctionalTests.js
      if: runner.os == 'Windows'
