name: Package .vsix

on:
  push:
    # tags:
    #   - '*'
    branches:
      - package-vsix

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install
    - run: npm install -g @vscode/vsce
    - run: vsce package
    - uses: actions/upload-artifact@v3
      with:
        name: vsix-package
        path: splunk-*.vsix
        if-no-files-found: error
