name: Package .vsix

on:
  push:
    tags:
      - '*'
    branches:
      - spl2-tests

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm --version
    - run: node --version
    - run: npm install
    - run: npm list
    - run: npm run compile
    - run: npm install -g @vscode/vsce
    - run: vsce package
    - uses: actions/upload-artifact@v3
      with:
        name: vsix-package
        path: splunk-*.vsix
        if-no-files-found: error
  
  integration-test:
    needs: package
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: vsix-package
    - run: pwd
    - run: ls -l *.vsix
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm --version
    - run: node --version
    - run: npm install
    - run: npm list
    - run: npm run compile-tests
    - run: echo "Run integration tests" && node ./out/test/runTest.js

